export const data = [
  {
    id: 1,
    src: './card1.png',
    brand: 'Ancienne Manufacture Royale',
    name: 'Чашка с блюдцем',
    material: 'Фарфор, эмаль',
  },
  {
    id: 2,
    src: './card2.png',
    brand: 'Bernardaud',
    name: 'Тарелка сервировочная',
    material: 'Фарфор, эмаль',
  },
  {
    id: 3,
    src: './card3.png',
    brand: 'Bernardaud',
    name: 'Сервиз 24 предмета',
    material: 'Фарфор, эмаль',
  },
  {
    id: 4,
    src: './card4.png',
    brand: 'Hermes',
    name: "Cheval d'Orient Чашка чайная с блюдцем 230мл",
    material: 'Фарфор, эмаль',
  },
  {
    id: 5,
    src: './card5.png',
    brand: 'Hermes',
    name: "Cheval d'Orient чайный набор, 6 предметов",
    material: 'Фарфор, эмаль, золото',
  },
  {
    id: 6,
    src: './card6.png',
    brand: 'J.Seignolles',
    name: 'Тарелка сервировочная, 30,5 см',
    material: 'Фарфор',
  },
  {
    id: 7,
    src: './card7.png',
    brand: 'J.Seignolles',
    name: 'Сервиз Renaissance, 12 предметов',
    material: 'Фарфор',
  },
];
